{application,erlang_otp,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{erlang_otp,[]}},
              {env,[]},
              {modules,[demo1,redis_app,redis_element,redis_store,redis_sup,
                        simple_redis]}]}.
